version: '3.4'

services:
  l1_chain:
    image: fueldev/l1chain:${DOCKER_TAG_L1_CHAIN:-latest}
    platform: linux/amd64
    build:
      context: ./docker/l1-chain/
    env_file:
      - ./envs/l1_chain.env
    ports:
      # expose the service to the host for integration testing
      - ${L1_CHAIN_HTTP_PORT:-8545}:9545
      - ${DEPLOYMENTS_PORT:-8080}:8081

  fuel_core:
    depends_on:
      - l1_chain
    image: fueldev/fuelcore:${DOCKER_TAG_FUEL_CORE:-latest}
    platform: linux/amd64
    build:
      context: ./docker/fuel-core/
    env_file:
      - ./envs/fuel_core.env
    environment:
      L1_CHAIN_HTTP: http://l1_chain:9545
      DEPLOYMENTS_HTTP: http://l1_chain:8081/deployments.local.json
    ports:
      # expose the service to the host for integration testing
      - ${FUEL_CORE_HTTP_PORT:-4000}:4001
