name: 'Rust & Forc Setup'

inputs:
  rust-version:
    default: 1.74.1

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: clippy, rustfmt

    - name: Init cache
      uses: Swatinem/rust-cache@v2
