[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "bridge_fungible_token"

[dependencies]
contract_message_receiver = { path = "../bridge-message-predicates/contract-message-receiver" }
# TODO: lock a specific release
reentrancy = { git = "https://github.com/FuelLabs/sway-libs" }
