/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FuelMessagePortalInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "ETH_DECIMALS()": FunctionFragment;
    "FUEL_BASE_ASSET_DECIMALS()": FunctionFragment;
    "MAX_MESSAGE_DATA_SIZE()": FunctionFragment;
    "PAUSER_ROLE()": FunctionFragment;
    "depositETH(bytes32)": FunctionFragment;
    "fuelBaseAssetDecimals()": FunctionFragment;
    "fuelChainStateContract()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "incomingMessageSuccessful(bytes32)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "messageSender()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "relayMessage(tuple,tuple,tuple,tuple,tuple)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "sendMessage(bytes32,bytes)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "unpause()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ETH_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FUEL_BASE_ASSET_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MESSAGE_DATA_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fuelBaseAssetDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fuelChainStateContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "incomingMessageSuccessful",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "messageSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayMessage",
    values: [
      {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      { key: BigNumberish; proof: BytesLike[] },
      { key: BigNumberish; proof: BytesLike[] }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ETH_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FUEL_BASE_ASSET_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MESSAGE_DATA_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fuelBaseAssetDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fuelChainStateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incomingMessageSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MessageRelayed(bytes32,bytes32,bytes32,uint64)": EventFragment;
    "MessageSent(bytes32,bytes32,uint256,uint64,bytes)": EventFragment;
    "Paused(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageRelayed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export class FuelMessagePortal extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FuelMessagePortalInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    ETH_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    "FUEL_BASE_ASSET_DECIMALS()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MAX_MESSAGE_DATA_SIZE(overrides?: CallOverrides): Promise<[BigNumber]>;

    "MAX_MESSAGE_DATA_SIZE()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "PAUSER_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    depositETH(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositETH(bytes32)"(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fuelBaseAssetDecimals(overrides?: CallOverrides): Promise<[number]>;

    "fuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<[number]>;

    fuelChainStateContract(overrides?: CallOverrides): Promise<[string]>;

    "fuelChainStateContract()"(overrides?: CallOverrides): Promise<[string]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    incomingMessageSuccessful(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "incomingMessageSuccessful(bytes32)"(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    messageSender(overrides?: CallOverrides): Promise<[string]>;

    "messageSender()"(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<[string]>;

    relayMessage(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "relayMessage((bytes32,bytes32,bytes32,uint64,bytes),(bytes32,uint64,uint64,bytes32),(bytes32,uint64,uint64,uint64,uint64,uint64,bytes32,bytes32),(uint256,bytes32[]),(uint256,bytes32[]))"(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "sendMessage(bytes32,bytes)"(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "upgradeTo(address)"(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "upgradeToAndCall(address,bytes)"(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

  FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_MESSAGE_DATA_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_MESSAGE_DATA_SIZE()"(overrides?: CallOverrides): Promise<BigNumber>;

  PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

  "PAUSER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  depositETH(
    recipient: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositETH(bytes32)"(
    recipient: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fuelBaseAssetDecimals(overrides?: CallOverrides): Promise<number>;

  "fuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<number>;

  fuelChainStateContract(overrides?: CallOverrides): Promise<string>;

  "fuelChainStateContract()"(overrides?: CallOverrides): Promise<string>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  incomingMessageSuccessful(
    messageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "incomingMessageSuccessful(bytes32)"(
    messageId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    fuelChainState: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    fuelChainState: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  messageSender(overrides?: CallOverrides): Promise<string>;

  "messageSender()"(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  "proxiableUUID()"(overrides?: CallOverrides): Promise<string>;

  relayMessage(
    message: {
      sender: BytesLike;
      recipient: BytesLike;
      nonce: BytesLike;
      amount: BigNumberish;
      data: BytesLike;
    },
    rootBlockHeader: {
      prevRoot: BytesLike;
      height: BigNumberish;
      timestamp: BigNumberish;
      applicationHash: BytesLike;
    },
    blockHeader: {
      prevRoot: BytesLike;
      height: BigNumberish;
      timestamp: BigNumberish;
      daHeight: BigNumberish;
      txCount: BigNumberish;
      outputMessagesCount: BigNumberish;
      txRoot: BytesLike;
      outputMessagesRoot: BytesLike;
    },
    blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
    messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "relayMessage((bytes32,bytes32,bytes32,uint64,bytes),(bytes32,uint64,uint64,bytes32),(bytes32,uint64,uint64,uint64,uint64,uint64,bytes32,bytes32),(uint256,bytes32[]),(uint256,bytes32[]))"(
    message: {
      sender: BytesLike;
      recipient: BytesLike;
      nonce: BytesLike;
      amount: BigNumberish;
      data: BytesLike;
    },
    rootBlockHeader: {
      prevRoot: BytesLike;
      height: BigNumberish;
      timestamp: BigNumberish;
      applicationHash: BytesLike;
    },
    blockHeader: {
      prevRoot: BytesLike;
      height: BigNumberish;
      timestamp: BigNumberish;
      daHeight: BigNumberish;
      txCount: BigNumberish;
      outputMessagesCount: BigNumberish;
      txRoot: BytesLike;
      outputMessagesRoot: BytesLike;
    },
    blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
    messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    recipient: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "sendMessage(bytes32,bytes)"(
    recipient: BytesLike,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unpause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "upgradeTo(address)"(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "upgradeToAndCall(address,bytes)"(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_MESSAGE_DATA_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_MESSAGE_DATA_SIZE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

    "PAUSER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    depositETH(recipient: BytesLike, overrides?: CallOverrides): Promise<void>;

    "depositETH(bytes32)"(
      recipient: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    fuelBaseAssetDecimals(overrides?: CallOverrides): Promise<number>;

    "fuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<number>;

    fuelChainStateContract(overrides?: CallOverrides): Promise<string>;

    "fuelChainStateContract()"(overrides?: CallOverrides): Promise<string>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    incomingMessageSuccessful(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "incomingMessageSuccessful(bytes32)"(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      fuelChainState: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address)"(
      fuelChainState: string,
      overrides?: CallOverrides
    ): Promise<void>;

    messageSender(overrides?: CallOverrides): Promise<string>;

    "messageSender()"(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<string>;

    relayMessage(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: CallOverrides
    ): Promise<void>;

    "relayMessage((bytes32,bytes32,bytes32,uint64,bytes),(bytes32,uint64,uint64,bytes32),(bytes32,uint64,uint64,uint64,uint64,uint64,bytes32,bytes32),(uint256,bytes32[]),(uint256,bytes32[]))"(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "sendMessage(bytes32,bytes)"(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeTo(address)"(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeToAndCall(address,bytes)"(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AdminChanged(
      previousAdmin: null,
      newAdmin: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    BeaconUpgraded(
      beacon: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    Initialized(version: null): TypedEventFilter<[number], { version: number }>;

    MessageRelayed(
      messageId: BytesLike | null,
      sender: BytesLike | null,
      recipient: BytesLike | null,
      amount: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      {
        messageId: string;
        sender: string;
        recipient: string;
        amount: BigNumber;
      }
    >;

    MessageSent(
      sender: BytesLike | null,
      recipient: BytesLike | null,
      nonce: BigNumberish | null,
      amount: null,
      data: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, string],
      {
        sender: string;
        recipient: string;
        nonce: BigNumber;
        amount: BigNumber;
        data: string;
      }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;

    Upgraded(
      implementation: string | null
    ): TypedEventFilter<[string], { implementation: string }>;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_MESSAGE_DATA_SIZE(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_MESSAGE_DATA_SIZE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "PAUSER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    depositETH(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositETH(bytes32)"(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fuelBaseAssetDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    "fuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    fuelChainStateContract(overrides?: CallOverrides): Promise<BigNumber>;

    "fuelChainStateContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incomingMessageSuccessful(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "incomingMessageSuccessful(bytes32)"(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address)"(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    messageSender(overrides?: CallOverrides): Promise<BigNumber>;

    "messageSender()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<BigNumber>;

    relayMessage(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "relayMessage((bytes32,bytes32,bytes32,uint64,bytes),(bytes32,uint64,uint64,bytes32),(bytes32,uint64,uint64,uint64,uint64,uint64,bytes32,bytes32),(uint256,bytes32[]),(uint256,bytes32[]))"(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendMessage(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "sendMessage(bytes32,bytes)"(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "upgradeTo(address)"(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "upgradeToAndCall(address,bytes)"(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ETH_DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FUEL_BASE_ASSET_DECIMALS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "FUEL_BASE_ASSET_DECIMALS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_MESSAGE_DATA_SIZE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MAX_MESSAGE_DATA_SIZE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PAUSER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositETH(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositETH(bytes32)"(
      recipient: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fuelBaseAssetDecimals(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fuelBaseAssetDecimals()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fuelChainStateContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fuelChainStateContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incomingMessageSuccessful(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "incomingMessageSuccessful(bytes32)"(
      messageId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      fuelChainState: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    messageSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "messageSender()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayMessage(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "relayMessage((bytes32,bytes32,bytes32,uint64,bytes),(bytes32,uint64,uint64,bytes32),(bytes32,uint64,uint64,uint64,uint64,uint64,bytes32,bytes32),(uint256,bytes32[]),(uint256,bytes32[]))"(
      message: {
        sender: BytesLike;
        recipient: BytesLike;
        nonce: BytesLike;
        amount: BigNumberish;
        data: BytesLike;
      },
      rootBlockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        applicationHash: BytesLike;
      },
      blockHeader: {
        prevRoot: BytesLike;
        height: BigNumberish;
        timestamp: BigNumberish;
        daHeight: BigNumberish;
        txCount: BigNumberish;
        outputMessagesCount: BigNumberish;
        txRoot: BytesLike;
        outputMessagesRoot: BytesLike;
      },
      blockInHistoryProof: { key: BigNumberish; proof: BytesLike[] },
      messageInBlockProof: { key: BigNumberish; proof: BytesLike[] },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "sendMessage(bytes32,bytes)"(
      recipient: BytesLike,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "upgradeTo(address)"(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "upgradeToAndCall(address,bytes)"(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
