[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "test_deposit_recipient_contract"

[dependencies]
contract_message_receiver = { path = "../../message-predicates/contract-message-receiver" }
