/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.70.0
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

export type { BridgeFungibleTokenAbi } from './BridgeFungibleTokenAbi';

export { BridgeFungibleTokenAbi__factory } from './factories/BridgeFungibleTokenAbi__factory';
