[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "reentrancy-attacker.sw"
license = "Apache-2.0"
name = "reentrancy-attacker"

[dependencies]
contract_message_receiver = { path = "../../../message-predicates/contract-message-receiver" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.0" }
