name: Upgrade Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Target branch for the PR
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  upgrade-test-suite:
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.TENDERLY_RPC_URL }}
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.16.0
          pnpm-version: 9.0.6
      - uses: FuelLabs/github-actions/setups/docker@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup-rust
      - name: Build project
        run: pnpm build
      - name: Run integration tests on a L1 fork after upgrading contracts
        run: |
          pnpm run test:integration:fork
