name: Verify Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Target branch for the PR
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-upgrade:
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.RPC_URL || 'https://sepolia.gateway.tenderly.co' }}
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'deploy/')
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.16.0
          pnpm-version: 9.0.6
      - name: Verify deployment bytecode
        run: |
          # Extract branch name from `GITHUB_HEAD_REF` (PR source branch)
          BRANCH_NAME=${{ github.head_ref }}

          # Remove the deploy/ prefix
          BRANCH_NAME=${BRANCH_NAME#deploy/}

          npx hardhat verify-deployment --network $BRANCH_NAME
        working-directory: ./packages/solidity-contracts
