name: Verify Deployment

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-upgrade:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'deploy/')
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.16.0
          pnpm-version: 9.0.6
      - name: Verify deployment bytecode
        run: |
          # Extract branch name from `GITHUB_REF`
          BRANCH_NAME=${{ github.ref }}

          # Remove the refs/heads/ prefix
          BRANCH_NAME=${BRANCH_NAME#refs/heads/deploy/}

          npx hardhat verify-deployment --network ${{ BRANCH_NAME }}
        working-directory: ./packages/solidity-contracts
